<?php

namespace App\Filament\Resources;

use App\Enums\DaysOfTheWeek;
use App\Filament\Resources\ClubResource\Pages;
use App\Filament\Resources\ClubResource\RelationManagers;
use App\Models\Club;
use Cheesegrits\FilamentGoogleMaps\Fields\Map;
use Cheesegrits\FilamentGoogleMaps\Widgets\MapTableWidget;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Pages\Page;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class ClubResource extends Resource
{
    protected static ?string $model = Club::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')->required(),
                Forms\Components\RichEditor::make('description'),
                Forms\Components\TextInput::make('website')->prefix('https://'),
                Forms\Components\CheckboxList::make('day_of_week')->options(DaysOfTheWeek::class),
                Forms\Components\TextInput::make('instagram')->prefix('@'),
                Forms\Components\TextInput::make('geocomplete'),
                Map::make("location") ->mapControls([
                    'mapTypeControl'    => true,
                    'scaleControl'      => true,
                    'streetViewControl' => true,
                    'rotateControl'     => true,
                    'fullscreenControl' => true,
                    'searchBoxControl'  => false, // creates geocomplete field inside map
                    'zoomControl'       => false,
                ])
                    ->height(fn () => '400px') // map height (width is controlled by Filament options)
                    ->defaultZoom(5) // default zoom level when opening form
                    ->autocomplete('geocomplete') // field on form to use as Places geocompletion field
                    ->autocompleteReverse(true) // reverse geocode marker location to autocomplete field
                    ->reverseGeocode([
                        'street' => '%n %S',
                        'city' => '%L',
                        'state' => '%A1',
                        'zip' => '%z',
                    ]) // reverse geocode marker location to form fields, see notes below
                    ->debug() // prints reverse geocode format strings to the debug console
                    ->defaultLocation([39.526610, -107.727261]) // default for new forms
                    ->draggable() // allow dragging to move marker
                    ->clickable(true) // allow clicking to move marker
                    ->geolocate()
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }


    public static function getWidgets(): array
    {
        return parent::getWidgets(); // TODO: Change the autogenerated stub
    }


    public static function getPages(): array
    {
        return [
            'index' => Pages\ListClubs::route('/'),
            'create' => Pages\CreateClub::route('/create'),
            'edit' => Pages\EditClub::route('/{record}/edit'),
        ];
    }
}
